### ISSUE TITLE
[Not a Bug] FAQ (Work in progress)

### ISSUE THREAD

**Issue by HACKERALERT** [HACKERALERT/Picocrypt#101]
# Frequently Asked Questions
You may have some questions about how Picocrypt works, what you can do with it, or why it doesn't work. Most of your questions will probably be answered here, so read on!

**To do**
"Can I use Pico for my cloud storaged files?"
"Why there is a paranoid mode, is not Pico safe enough?
"Does my password strength matters?"
"Can I use Pico on older devices?"

## General
**Will Android/iOS be supported?**
No, I won't support Android or iOS because they are very different from desktop operating systems and require a lot of work to compile for. The native language for Android apps is Java and the native language for Apple is Swift, however, Picocrypt is written in Go. While Go does have some Android support, the underlying GUI library used by Picocrypt doesn't support Android. Fortunately, since Picocrypt is open source, there may be a community-based Android port in the future, which I would be happy to merge in and maintain. For iOS, it is much more difficult because Apple has deprecated OpenGL from iOS and macOS to push their own proprietary Metal framework. Picocrypt requires OpenGL to run, and if Apple doesn't support the widely-adopted standard, it is impossible to have an iOS app (shame on you, Apple).

**Why does my antivirus think Picocrypt is a virus?**
Unfortunately, due to the nature of Picocrypt, it can look like a virus to antiviruses. Picocrypt contains code for encryption, which is seen in ransomware, and also contains code to delete files (the "Delete files" feature), which also is seen in ransomware. So to an antivirus, Picocrypt can look malicious, however, it is not, so please submit it as a false positive to help out everyone.

**What file types can I encrypt?**
You can encrypt any types of files with Picocrypt, there is no limitation.

**Can I decrypt my files outside of Picocrypt?**
No, you will need to use Picocrypt to decrypt any files encrypted with Picocrypt. This is because Picocrypt uses its own header format.

**Can I change the extension of a Picocrypt volume?**
No, please don't do that. Picocrypt volumes will typically look something like `name.extension.pcv` and when decrypting, uses the `name.extension` as the output. If you remove the extension and rename your volume to `name.pcv`, then Picocrypt doesn't know what the original extension is and will decrypt to `name` with no extension. So make sure you don't do that.

**I want to help translate, how should I start?**
Click <a href="https://raw.githubusercontent.com/HACKERALERT/Picocrypt/main/README.md">here</a>, which will lead you to the homepage document. To translate, simply copy everything into a text editor and replace all English strings with their equivalent in your language. When you're done translating, fork this repo and create a new file under `translations` and put your translated file there. Then, send a PR. If you don't know how to do that, feel free to just send me the document and I will take it from there.

## Features
**Will Picocrypt accept new features?**
No, Picocrypt is considered feature-complete and won't be getting any new features. Unlike some other tools which try to constantly add new features and introduce new bugs and security holes, Picocrypt focuses on just a few features but doing each of them exceptionally well.

**Does Reed-Solomon affect the speed of encryption/decryption?**
It will only slow down your encryption speed under normal circumstances. If you decrypt a Reed-Solomon-encoded volume, it will decrypt at normal speed as long as there isn't any corruption. If there is corruption, however, Picocrypt will slow down significantly to rebuild the lost data. It will be slow, but remember, it's better to have your data back intact than not have it at all.

## Windows
**Picocrypt won't start. What should I do?**
First, try using `Picocrypt-NoGL.exe` instead of the standard `Picocrypt.exe`. The standard `Picocrypt.exe` uses hardware-accelerated OpenGL for drawing the UI, but on systems that don't have OpenGL support, `Picocrypt-NoGL.exe` will use Mesa3D's software renderer instead.

## macOS
**I can't open Picocrypt because it's from an unverified developer!**
Right click on `Picocrypt.app` and hit "Open". macOS will still not allow you to run Picocrypt, so right click on `Picocrypt.app` again and hit "Open", and you should get the option to run Picocrypt.

## Linux
**Should I use the .deb or AppImage?**
I generally recommend the .deb over the AppImage and Snapcraft because it is the most "native" and will run with the best performance, reliability, and consistency. There are situations, however, where the AppImage may be appealing, such as a live operating system like "Tails", or on a non-Debian based distro like Fedora or Arch. The Snap is provided as a fallback if you are unable to install the .deb or run the AppImage, and should be avoided when possible.

**Can I use Pico on live disk environments?**
Yes, Picocrypt fully supports any Debian-based live distro such as Tails.

**Comment by DillFrescott** [comment]
Good to know! :)
