### ISSUE TITLE
Hello, can you support the encrypted volume function like Veracrypt?  Or temporary decryption? 

### ISSUE THREAD

**Issue by ZhuningS** [HACKERALERT/Picocrypt#102]
Hello, can you support the encrypted volume function like Veracrypt?  Or temporary decryption?  That function is very convenient, each decompression is too much trouble

**Comment by ZhuningS** [comment]
I mean to prevent the leak of confidential files, and now every time the decompression is a plaintext file, you need to delete it manually, modify it and encrypt it again, so you can restore the deleted text file through the data recovery tool to break it.
Can you support anti-duplication, anti-replication, anti-moving, anti-size detection and other features?

Like the three ways of decryption on lockdir, it is easy to use the easy and safe mechanism to reveal the secret:
Image browsing: decrypt all files to a virtual disk, and decrypt faster than other methods.
Temporary decryption: a restore encryption window will appear when decrypted, and it can easily restore encryption.
Complete decryption: folder completely untied. You must reenter the password when you need to encrypt the article again.

Lockdir introduction:：https://www.gpsmap.cc/soft/11894.html
Will the other picocrypt be hacked by hackers?

**Comment by HACKERALERT** [comment]
That's too complicated and Picocrypt is not designed to cover every use case, it is designed to cover what most people would use it for. So in the case of temporary decryption, Picocrypt doesn't support it. If you really think about it, temporary decryption is not temporary, it's just decrypted and deleted and can still be recovered by advanced data recovery tools. The only true temporary decryption is to decrypt it and store it encrypted with the key in memory, and erase the key from memory when the files are no longer needed, but this doesn't work with native drive mounting.

> Will the other picocrypt be hacked by hackers?

?

**Comment by HACKERALERT** [comment]
Closing for now, see message on Reddit or Discord for more information.
