### ISSUE TITLE
Hi, picocrypt can encrypt large folders of several terabytes in Linux fast (encryption speed and security)? There are few such tools on the market. Can Picocrypt support fast encryption that only scrambles the file structure and encrypts the file header?

### ISSUE THREAD

**Issue by ZhuningS** [HACKERALERT/Picocrypt#105]
Hi, picocrypt can encrypt large folders of several terabytes in Linux fast (encryption speed and security)? There are few such tools on the market. Can Picocrypt support fast encryption that only scrambles the file structure and encrypts the file header?

Up to now, many of the tools on the market are either very slow to encrypt large folders or are insecure and lack compromise tools.

**Comment by HACKERALERT** [comment]
> Can Picocrypt support fast encryption that only scrambles the file structure and encrypts the file header?

If you only encrypt the file header, whatever that is, there is no encryption done to the data and it is still considered unencrypted. So any tool that only encrypts the header and scrambes the file structure doesn't actually protect your data at all.

However, Picocrypt has no size limit so you can encrypt multiple terabytes of data and Picocrypt has a good speed of about 200MB/s on a modern processor with fast storage. What is your use case for Picocrypt?

**Comment by HACKERALERT** [comment]
Closing for now, see message on Reddit or Discord for more information.
