### ISSUE TITLE
Picocrypt bug under Wayland

### ISSUE THREAD

**Issue by MasterKia** [HACKERALERT/Picocrypt#107]
OS: Fedora KDE 36 (running in VMWare)

Under the Wayland session, when I drag a file into the Picocrypt window nothing happens; even if I run `sudo ./Picocrypt.AppImage` and run Picocrypt as root still when I drag and drop a file into Picocrypt nothing happens.

But when I logout and login using the X11 session, there is no problem whatsoever.

Now I know you said [you're not a GNU/Linux nerd](https://github.com/HACKERALERT/Picocrypt/issues/59#issuecomment-1015011511), but is there something that I can do to diagnose this issue?

**Comment by HACKERALERT** [comment]
https://www.google.com/search?q=xwayland+drag+and+drop+broken
Looks like a common issue with Wayland itself, in particular XWayland which emulates calls for "legacy" applications like Picocrypt which use X11. Is there any terminal output when you run ./Picocrypt.AppImage? You can also try the .snap if you wish.

**Comment by HACKERALERT** [comment]
Closing for now, see message on Reddit or Discord for more information.
