### ISSUE TITLE
Doesn't start on Windows

### ISSUE THREAD

**Issue by beerisgood** [HACKERALERT/Picocrypt#11]
If i try starting Picocrypt.exe (Version 1.11), i got this window:
![image](https://user-images.githubusercontent.com/9625159/112758722-1f00c800-8ff0-11eb-8552-44ee800f22ec.png)

So, the exe is just a .vbs file?

**Comment by HACKERALERT** [comment]
That's quite odd. No, Picocrypt is not a .vbs, but it uses a .vbs to start the main process which contains the Python runtime. Someone on Reddit also said the same thing. I think Windows must of pushed some updates that caused this issue. I'll look into it.

**Comment by HACKERALERT** [comment]
I think I might know why. I've created a new executable called Picocrypt-update.exe in v1.10. Can you try it and tell me if it works?

**Comment by beerisgood** [comment]
> I think I might know the cause of this issue. I've created a new executable called Picocrypt-update.exe in v1.10. Can you try it and tell me if it works?

starting 1.10 doesn't work neither.
A solution without using VBS nor other stuff from %temp% would be nice.

**Comment by HACKERALERT** [comment]
Can you post a screenshot, or is it the same as the screenshot above? I'm trying a new method right now that doesn't require a .vbs.

**Comment by beerisgood** [comment]
> Can you post a screenshot, or is it the same as the screenshot above? I'm trying a new method right now that doesn't require a .vbs.

same screenshot

**Comment by HACKERALERT** [comment]
Really sorry, give me some time to figure this out. It's working fine on my Windows, probably because it hasn't updated yet... And all previous versions now don't work either?

**Comment by beerisgood** [comment]
Don't think so.
This also shouldn't be Windows itself but with security restrictions i use.
Scripts can't be started on my system because security reasons and as your program is built with security in mind, this shouldn't be a problem.

**Comment by HACKERALERT** [comment]
I understand that security software should run under secure settings, so I've tried my best and created another update. Can you try Picocrypt-update3.exe under v1.11? Let me know how it goes.

**Comment by beerisgood** [comment]
It works! 👍

**Comment by HACKERALERT** [comment]
Great. Since that exe is only for testing, the secure feature doesn't work. In v1.12, I'll upload a good copy that will be named Picocrypt-NoScript.exe.

**Comment by beerisgood** [comment]
Awesome!
Thanks also for that amazingly fast fix!

**Comment by CuteRose1** [comment]
I am using a 32 bit desktop computer with Windows 8.1 and I ahve tried 7 releases of Picocrypt and some of them were not compatible and the rest do not even open , like I click on it and it does not open , No response at all. I tried the installer version but same problem.

I really wanna try this app , is there any solution?
And would you mind telling me on what kind of computer does the last release work? the one that was released 7 hours ago.
