### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by CaptainQuake** [HACKERALERT/Picocrypt#111]
1) Encryption of few files at the same time results in merging them into one big file. Ability to encrypt each file separately is needed (encryption of few files => separate result for each file)

2) Example: I encrypted file called "MyWallet.key" and got output "MyWallet.key.pcv". I renamed it to "DSC0782.jpg", so nobody will understand what is it.
If I'll just append ".pcv" ("DSC0782.jpg.pcv"), then after decryption I'll get "DSC0782.jpg" and I havo to manually rename it back to "MyWallet.key". So there's also needed ability to save original file name independently from the name of encrypted file.

**Comment by UberGuidoZ** [comment]
Looks like someone needs to fork it and be the new maintainer for a year. There are 55 forks! Who are we trusting?

**Comment by HACKERALERT** [comment]
Picocrypt isn't accepting any new features, as it would make Picocrypt not so simple anymore.

If you only have a few files, just do them manually, by hand. If you have lots of files, just encrypt them together. There's really no reason to do anything else.

The naming convention is the simplest and most reliable. Just add a ".pcv" when encrypting and strip the ".pcv" when decrypting. Anything more than that I think is unnecessary complexity.
