### ISSUE TITLE
Picocrypt 1.11 Broken .app file

### ISSUE THREAD

**Issue by swoah** [HACKERALERT/Picocrypt#12]
Not sure if you're aware of this or not, but Picocrypt 1.11's download features a broken .app file.
![image](https://user-images.githubusercontent.com/52900125/113342037-95087600-92f3-11eb-9f67-0784473fb6eb.png)

1.10 works fine, however.

**Comment by HACKERALERT** [comment]
Well that's quite odd. Let me look into it.

**Comment by HACKERALERT** [comment]
Would you mind trying `Picocrypt-update.app.zip` under v1.11 and telling me how it goes? Thanks.

**Comment by swoah** [comment]
It works now! Thanks for the quick fix.

**Comment by HACKERALERT** [comment]
Really? Wow, I wasn't expecting that to fix it. :)

**Comment by HACKERALERT** [comment]
If we're all good, can we close this issue?
