### ISSUE TITLE
If the file is renamed, there's no way to change it back?

### ISSUE THREAD

**Issue by OrangeFox2000** [HACKERALERT/Picocrypt#125]
Hello there, I really appreciate you for creating this amazing software.
One little thing, when I encrypt a file the name will be "Encrypted.zip.pcv" and I renamed the file and removed the "pcv" and it changed to a zip file which if I immediately select the zip file and press "ctrl + z" it will undo the change I made but after certain amount of time I can't undo it. Now I renamed it myself just to test if I can change it back but what if someone renames the file and remove "pcv" in the name and change the file to a zip? then I can't decrypt my files? what will be the solution then? 
Please let me know if there's any solution
Thank you so very much

**Comment by HACKERALERT** [comment]
Yeah, ".pcv" must be in the filename, specifically at the end, for Picocrypt to recognize it as a volume. If it isn't in the filename, then Picocrypt will automatically assume it's a file you want to encrypt. If you know that a file is a Picocrypt volume, you add back the ".pcv" and drag it into Picocrypt, which will then read the header and tell you whether the file you dropped is indeed a volume or not. That's really all you can do though, other than making sure whoever is using your computer is trustable :)

Tip: If someone was to rename Encrypted.zip.pcv to Encrypted.zip, the zip file wouldn't be valid and you wouldn't be able to open it. That's a big hint right there!

**Comment by HACKERALERT** [comment]
@OrangeFox2000 Hope this answers your question. I'll close this issue now for now, but please feel free to reopen it if you have any further questions. Good day!

**Comment by OrangeFox2000** [comment]
Hello again

I didn't question the security of Picocrypt, I know that even if someone changes Encrypted.zip.pcv to a zip file there is still no way to open the file. My point was the ability to undo the change in filename which seems to be impossible as you have kindly explained. However I did try to add ".pcv" back but it didn't change the filename, the file remained as a zip file and PicoCrypt didn't recognize it as a file to decrypt and in fact it was ready to encrypt it all over agin.

I just figured a solution on my own though, what if we would use PicoCrypt to encrypt our files and then put the Encrypted.zip.pcv in a zip file with a diffrent password to make sure nobody can rename it? if there's a better way please do let me know.

**Comment by HACKERALERT** [comment]
Aha, that's what you meant. Yes, that works. I have extensions shown by default so I didn't realize it was impossible to add ".pcv" when extensions are hidden. Glad to hear you have it solved!
