### ISSUE TITLE
The Password checker is wrong

### ISSUE THREAD

**Issue by tegutistgut** [HACKERALERT/Picocrypt#13]
Idk how it's called, but when setting a password for the file, it says that "password1." is strong (green bar) and "password1" is medium strong (orange bar)

You could solve this by implementing "zxcvbn"

Thanks

**Comment by HACKERALERT** [comment]
Yeah, the password checker was crammed in to v1.12.1. Thanks for suggesting "zxcvbn", I actually didn't know about that before. It seems like a great password strength checker to implement. I think I'll add it in v1.13.

**Comment by HACKERALERT** [comment]
zxcvbn is implemented in v1.14, so I'm closing this issue. You may reopen it if you like 👍 .
