### ISSUE TITLE
A small suggestion 

### ISSUE THREAD

**Issue by Tsu-gu** [HACKERALERT/Picocrypt#137]
I like the simplicity and small size of Picocrypt, and agree that it is feature complete. The part with dropping folders into the app itself  works great, though it might not work on some desktop environments/window managers, and it would be a pity if somebody wasn't able to use Picocrypt simply becaouse his DE doesn't support drag and drop, or the feature has been broken by an update. So maybe it's not a bad idea to add an area where you can manually type in names of the folders/files?

**Comment by Tsu-gu** [comment]
I can't name any DEs/WMs, but you never know what will be broken by the next update. I do agree that it is very unlikely that this specific function of a DE will get broken, but things never break as we expect.

**Comment by HACKERALERT** [comment]
I still think it's unnecessary to support these very unlikely scenarios. There will always be systems that software can't support, and trying to support them will only increase codebase size and introduce more places for bugs. For almost all systems, drag and drop will be present and you can use Picocrypt. For the 0.01% that don't have drag and drop, they might as well use a command line encryption tool. So I won't be adding support for manually selecting files. I appreciate your suggestion and thoughfulness though! Thanks for letting me know about this situation, even if I have decided to not worry about it 👍 .

**Comment by HACKERALERT** [comment]
@Tsu-gu 

In a spark of motivation, I've finally added a simple CLI to Picocrypt! So on systems where the UI won't run, you can still encrypt files through the CLI. Let me know what you think.

https://github.com/HACKERALERT/Picocrypt/tree/main/cli
