### ISSUE TITLE
Feature Request : File & Folder Names Obfuscation

### ISSUE THREAD

**Issue by Zyxyx** [HACKERALERT/Picocrypt#14]
Would it be possible to implement this feature to (optionally) hide the names of the encrypted file(s) and folder(s) ?

In some cases those names may contain valuable information on the files and folders contents  that one would prefer to keep private / concealed / protected from outside view.

To further clarify this request, it is probably easiest to refer to a similar feature that worked quite well in the GUI version of Kryptor (now defunct in the latest CLI only version), as described on the following page :

https://www.kryptor.co.uk/technical-details   (See : "File name obfuscation")

To check or test this, you can download the last (portable) GUI version of that software there :

https://github.com/samuel-lucas6/Kryptor/releases/tag/v2.2.2

Thanks for all the hard work already done on Picocrypt !
It is well on its way to becoming a must have security tool.

**Comment by HACKERALERT** [comment]
Congrats on your first issue! Picocrypt already does this. When encrypting multiple files and/or folders, they are compressed into a zip file and the whole zip file (including file names, etc.) is encrypted. There's no way to see the file/folder names without decrypting it.

**Comment by Zyxyx** [comment]
> There's no way to see the file/folder names without decrypting it.

Indeed, I am sorry I did not try the latest version before opening this issue.
Now its title is obviously not that accurate anymore... but, after testing the current implementation, I have to say I do not think it is a very convenient way to handle encrypted files / folders.

As it is not possible to browse the encrypted archive from within Picocrypt and to access the specific file(s) you need, you have to first decrypt all its content (which can take a lot of time), then unzip that one file you need.

If you want to share encrypted files and make it possible to decrypt only one at a time (let's say after identifying it based on its size... *), you have to repeat the encryption process as many times as you have files.

(*) ... or directly by name if you could see it - with the correct password - from within Picocrypt)

I realize it is somewhat of a multiple features request, here, but it is what I am missing from the way this was working in Kryptor, hence my original post. Another advantage was you did not have to unzip after decryption.

Right now, Picocrypt is a good solution to archive data with a high sense of security but I do not find it suitable if you need to access files frequently or encrypt several files individually. The same is true if you want to add / remove / modify / rename file(s) in one encrypted folder.

What do you think ?

**Comment by HACKERALERT** [comment]
Hey, I definitely agree with you. I'll start off by saying that Picocrypt is still in its infancy, and as of May, it's only 4 months old. Kryptor is (IIRC) 10 months old, so it's been through a lot more development than Picocrypt, as the developer has a "6 month advantage". As time goes on, I'll address the issues that come up (such as the ones you pointed out), and eventually, Picocrypt will be a viable alternative to Kryptor and maybe even VeraCrypt.

>As it is not possible to browse the encrypted archive from within Picocrypt and to access the specific file(s) you need, you have to first decrypt all its content (which can take a lot of time), then unzip that one file you need.

Yes, I know it can be a hassle. I'll point out the two reasons that are causing this. The first one is that currently, all versions up to v1.12.1 (the latest) are written in Python, which is known to be a slow language. I've been working hard at porting Picocrypt from Python to Go, which is _much_ faster, so in the next release (v1.13), you should be able to get speeds more then twice of previous versions, at around ~200MB/s, which should be reasonble. The second point is that currently, Picocrypt is a file encryption tool, so it's mean for encrypting/decrypting multiple files and folders in bulk, but not manage them individually. I think what you're refering to a sort of "VeraCrypt volume" thing, where you can browse files and have them encrypted/decrypted "on-the-fly" when you need them. This feature isn't in Picocrypt currently, but it's planned, and the feature will be called "Volume encryption" or something like that.

Currently, Picocrypt has only one function -- encryption, but I've been working on adding multiple more, such as a file shredder, checksum generator, etc. Eventually, I hope to add a volume-based encryption feature, where you can drag files into Picocrypt to add it to a volume, and drag a file from inside the window to a file manager outside to automatically decrypt the items you dragged out, and not the whole volume.

Anyways, I will admit that I have a pretty busy schedule, so Picocrypt won't become something like VeraCrypt in the near couple of months, but as time permits and as people contribute to Picocrypt by creating pull requests, etc., I think that we can help Picocrypt mature into something that satifies everyone, while keeping security at its heart.

**Comment by Zyxyx** [comment]
Thank you for your quick answer.

> I think what you're refering to a sort of "VeraCrypt volume" thing, where you can browse files and have them encrypted/decrypted "on-the-fly" when you need them.

I am not looking for another VeraCrypt or Cryptomator or other utilities like those. On the contrary...

What I think is missing is a small in size and portable tool (with a GUI for non CLI proficient users like myself) that you can use without the need to encrypt the whole disk or create a 'vault' outside of which files are unencrypted.

A software light enough to be quickly downloaded or easily kept with the file(s) you would want to decrypt as needed. One you could share with someone else along with one or a selection (!) of files / folders encrypted (with the same password in a single operation). But not necessarily all of them so they should not be in an archive kind of file (there are other applications to do that : compress and encrypt content, except for filenames). And then optionally a way to identify an encrypted file / folder by revealing its original name when 'browsing' from within the encryption software (with the correct password of course).

I am well aware that this description is probably not very clear - not enough anyway, which led to your previous answer - and I again feel that the best illustration of these features is to follow the two links given in my original post.

I completely understand this may not be the direction Picocrypt will take, but this is what I have not been able to find elsewhere.

That said, thank you for what it does already ; it seems to do it well. And I'll certainly keep an eye on your work to see how 'Pico' will grow in the future.

**Comment by HACKERALERT** [comment]
I still have many core features that I need to implement. Once Picocrypt is mature enough, I'll be able to add more "uncommon" features such as the one you requested.
