### ISSUE TITLE
Application crashing/exiting continuously 

### ISSUE THREAD

**Issue by Wffv9FNa** [HACKERALERT/Picocrypt#144]
I'm having an issue where Picocrypt keeps closing after around 20 seconds.
This happens regardless of whether an encryption/decryption is happening or not.
Does this application write logs anywhere as I'm unsure what is causing this?
I'm running **Windows 10 Pro 64-bit** (10.0, Build 19044) and using the latest **1.31** .exe stable release.
Steps to recreate:
1. Launch Picocrypt.exe
2. Wait 10-20 seconds
3. Application exits with no message or error

**Comment by HACKERALERT** [comment]
Thanks for reporting this issue. I'm not sure what's happening since I
can't recreate the issue. Picocrypt is portable so it doesn't leave any
logs, but you can see what caused the crash if you run it in the command
prompt. So, trying opening a command prompt in the same folder and run
"Picocrypt.exe" and show me the output. Thanks!

**Comment by Wffv9FNa** [comment]
I've ran the executable from command prompt but unfortunately no output was given.
I also ran ProcMon but again no real output of interest that I can see.
I have a suspicious there must be some software conflict as I've just left it running on my laptop and so far it hasn't exited.

![2023-01-28_00h15m34s_vivaldi](https://user-images.githubusercontent.com/63041557/215229036-b5173302-ae5d-477a-9a08-aaee3e187382.png)
![2023-01-28_00h14m11s_cmd](https://user-images.githubusercontent.com/63041557/215229038-351b02d2-c0b4-44bb-b333-487700764745.png)

**Comment by HACKERALERT** [comment]
Yeah that's very weird. If it's an issue with Picocrypt, then there should
be errors logged to the command prompt, but there aren't, so it's likely an
issue on your side. Try whitelisting Picocrypt in your antivirus and
updating your Windows before trying again. Maybe also try an older version
of Picocrypt. Other than that though, I don't think there's much I can do
about it 😅

**Comment by Wffv9FNa** [comment]
So it seems antivirus was the culprit after all. Despite being whitelisted the AV was obviously still killing the process anyway as I've just tested completely turning off the AV and Picocrypt has stayed open.
(AV is Webroot SecureAnywhere).
Thanks for responding! :)
