### ISSUE TITLE
Discussion:Android Apk

### ISSUE THREAD

**Issue by DeMoN100** [HACKERALERT/Picocrypt#145]
Hello I saw tjeres no discussion board so I decided to create this to ask. Picocrypt is so great & being only 3MB is there any possibility to turn this into an android apk & get it in f-droid?

**Comment by HACKERALERT** [comment]
As mentioned in the FAQ, I don't intend to make an Android app because it's very different from a desktop app and I would need to write it from scratch. I don't have much experience with mobile app development either. If someone can create an Android app, I may consider linking to it in the README.
