### ISSUE TITLE
several viruses found

### ISSUE THREAD

**Issue by zadkiel0** [HACKERALERT/Picocrypt#146]
![image](https://user-images.githubusercontent.com/94993487/219933134-b07497be-36c6-4cb4-b9b5-8344b4e6ac78.png)
i scanned the exe file for windows and it showed all these as viruses in that file. i scanned it in virus total , i have been using pico for a while what does this mean have i been cheated by you, did leave all these viruses in it?

**Comment by HACKERALERT** [comment]
No, antiviruses are well-known to be faulty with FOSS software. On the outside, Picocrypt contains code to encrypt files and delete files, so it looks like ransomware. Combine that with the fact that Picocrypt is compressed with UPX, a tool commonly used to obfuscate malware, and you get a recipe for disaster. But no, Picocrypt is not a virus and never has been or will be. If you don't believe me, go download UPX 4.0.1 and run `upx -d` on the latest Picocrypt.exe to extract the raw executable. Now upload that to VirusTotal and take another look. You'll notice that there are only two "detections" now, both of which are obscure antiviruses that nobody uses.
![image](https://user-images.githubusercontent.com/48808396/219957847-8a5bc1aa-e1d3-42b3-b406-54cd5d4ea1c9.png)
https://www.virustotal.com/gui/file/a09b6fdb0bfce4f72adf8b351136137f9c537a0996e3d3d9cf5e6c67ba4fbfb2/detection

So no, Picocrypt is not a virus. If you still don't believe me, you can run from source :)

**Comment by zadkiel0** [comment]
so noi backdoor is enabled in it right? i was using the portable version . the thing that concerned me was how a not installed tool effects my system iwas not even running anything
thank you for solving my concern!!! its the best encryption tool i have ever used

**Comment by HACKERALERT** [comment]
No, there's no backdoor or virus. Picocrypt's source code doesn't even contain the module needed to connect to the internet, so a backdoor isn't possible in the first place.
