### ISSUE TITLE
Urgent decryption!

### ISSUE THREAD

**Issue by MrFr11man** [HACKERALERT/Picocrypt#147]
I would like to apologize right away for the trouble and it is possible that I am addressing a question that does not concern you ... When transferring data to another PC using the Laplink PCmover program, I received a 110Gb .pcv file which now I cannot decrypt in any way ....  I'm asking for help!!  I've tried to open everything I can!!!  there are 4 years of life and work, money, documents...😭 And all this data was needed yesterday...

**Comment by HACKERALERT** [comment]
Take a deep breath, you'll likely be fine. Can you tell me approximately how long ago the volume was created?

**Comment by MrFr11man** [comment]
Just Saturday. The thing is that I used not official PCmover...🤦‍♂️

**Comment by HACKERALERT** [comment]
What's the error message in Picocrypt?

**Comment by MrFr11man** [comment]
there is no error there, I wrote above, this encrypted pcv container was created in PCmoover and I did not enter the passwords that are needed for decryption by your program.

**Comment by HACKERALERT** [comment]
So you've never used Picocrypt but somehow the software you used created a Picocrypt volume?

**Comment by MrFr11man** [comment]
your program is the only one that works with .pcv files, I have already tried everything else and it did not work ...
Just decided to ask your help if possible...

**Comment by HACKERALERT** [comment]
![image](https://user-images.githubusercontent.com/48808396/220012710-44a3b541-05c2-43e3-a51a-c28da985c689.png)
Ah so it seems like .pcv files are not specific to Picocrypt and may be part of PC Mover. Have you tried "opening" the .pcv file in PC Mover on your new PC?

**Comment by HACKERALERT** [comment]
![image](https://user-images.githubusercontent.com/48808396/220012852-846c6b8d-7f57-4d4b-b4f3-9cf5259918c3.png)
Multiple sources seem to say that PC Mover uses .pcv files, so it's likely not related to Picocrypt which just happens to use the same file extension. Try to see if you can open or restore the .pcv file within PC Mover.

**Comment by HACKERALERT** [comment]
https://help.laplink.com/how-to-use-file-based-transfer

**Comment by MrFr11man** [comment]
Yes, of course. But PCmoover just like freezing at at the time of calculating the required time for data transfer.and that all...

**Comment by HACKERALERT** [comment]
Ah well I guess I can't really help with that since the .pcv file has no relationg to Picocrypt. Try updating PCmover or asking for help in a related forum?

**Comment by MrFr11man** [comment]
I feel like I'm totally screwed... thanks for taking the time!  have a nice day!)

**Comment by HACKERALERT** [comment]
Best of luck!
