### ISSUE TITLE
What the perpouse of the key if you cant use it to decrypt files

### ISSUE THREAD

**Issue by Minehors** [HACKERALERT/Picocrypt#148]
You need to still write the password is this common behaviar or i'm missing something or missunderstand this tool?

So whats the point on creating a key file then if we cant use it to decrypt so we can use the master password for ourselfs

**Comment by HACKERALERT** [comment]
I don't quite understand what you are asking. You can use a password without any keyfiles. You can use a keyfile without any password. You can also use any combination of password and keyfiles.

**Comment by HACKERALERT** [comment]
You have to encrypt the file without using a password otherwise you will be required to enter a password when decrypting. Try encrypting the files again but leave the password fields empty when using a keyfile.

**Comment by Minehors** [comment]
> You have to encrypt the file without using a password otherwise you will be required to enter a password when decrypting. Try encrypting the files again but leave the password fields empty when using a keyfile.

Ok nice that was what i was trying to do thanks
