### ISSUE TITLE
[Suggestion] Encrypt files in a folder individually instead of packing the folder into a zip package.

### ISSUE THREAD

**Issue by AsuxAX** [HACKERALERT/Picocrypt#153]
I think a option to encrypt files individually and recursively could be useful for some.

**Comment by HACKERALERT** [comment]
Yeah this has been requested multiple times in the past, to which I have said no. But it looks like a lot of people want this feature, so I think I will give it a go. I'm busy at the moment so it may take a while to implement, but I'll keep this issue open until then.

**Comment by AsuxAX** [comment]
Alright, good to know.
10. Apr. 2023, 21:01 von ***@***.***:

**Comment by HACKERALERT** [comment]
In a spark of motivation, I've added a (simple) CLI to Picocrypt! It should allow you to encrypt your files how you want, including separately and recursively.

https://github.com/HACKERALERT/Picocrypt/tree/main/cli

**Comment by AsuxAX** [comment]
> In a spark of motivation, I've added a (simple) CLI to Picocrypt! It should allow you to encrypt your files however you want, including separately and recursively. Let me know if this is a "good enough" solution for this specific use case!
> 
> https://github.com/HACKERALERT/Picocrypt/tree/main/cli

That seems good enough. Though it would also be nice if it was in the GUI.

**Comment by HACKERALERT** [comment]
Yeah the CLI is meant to only work with one file. What I meant was that you can then use a script to encrypt however you want. For example, on Windows, you can do something like this to encrypt all PDFs in a folder:

```cmd
for %f in (*.pdf) do picocrypt -p password "%f"
```

**Comment by Minibus93** [comment]
Sorry to re open this, as I just read it.

Personally I'd say this feauture is important enough to be definitely worth of a spot in the GUI *IF* this will be the go-to way to encrypt files however the user wants.

I see this requested since ages and relegating it to CLI just doesn't seem to serve justice (unless CLI only is a temporary solution)

Just my 2 cents

**Comment by HACKERALERT** [comment]
That's fair. The one thing that bothers me is when I add a "Recursively" checkbox to the UI, now there's an empty space for another checkbox that's unfilled and looks rather ugly. Although I think if I add "Deniability" as well, I will kill two birds with one stone -- add the recursively encryption option and a plausible deniability option which seems to be a important feature in today's world. It'll take a while to make these two features, but I'm willing to spend some time and effort to make Picocrypt the go-to tool, as always. Let me know if you think these two features will finally make Picocrypt "complete". Thanks!

**Comment by HACKERALERT** [comment]
Closing in favour of #154.
