### ISSUE TITLE
Hardcoded dependency on particular version of glibC

### ISSUE THREAD

**Issue by CompuRoot** [HACKERALERT/Picocrypt#157]
AppImage shouldn't be dependent, the whole point of it is to work across platform without been dependent
```
picocrypt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by picocrypt)
```

**Comment by HACKERALERT** [comment]
I'm not a Linux user so I have no idea what that means or how to fix it lol
