### ISSUE TITLE
Comments are not encrypted (by default) and this is not mentioned in the program window

### ISSUE THREAD

**Issue by hakavlad** [HACKERALERT/Picocrypt#164]
README says "It's designed for maximal security, making absolutely no compromises security-wise", but comments are not encrypted by default and the user will not even be notified of this, unless he reads the README to a certain paragraph.

In my opinion, it would be good practice to notify users right in the program window that comments are not encrypted by default because not all users read the documentation beyond the first paragraph. This could reduce mortality among inattentive users.

**Comment by HACKERALERT** [comment]
Very good observation, thanks for pointing it out. Although I think most
people are sensible enough not to put sensitive data in the comments field,
I agree with you that adding something like a tooltip on hover would be a
good failsafe. It's would be a small change so I won't make a new release
just for it, but I'll keep this issue open as a reminder to add the warning
when I make the next release, whenever that may be. Thanks!

**Comment by HACKERALERT** [comment]
Added this to the changelog for the next release, so I'll close it here to keep things clean and organized.
