### ISSUE TITLE
[WEAK KEYS] XORing keyfile digests with each other is bad practice

### ISSUE THREAD

**Issue by hakavlad** [HACKERALERT/Picocrypt#170]
Using a pair of identical keyfiles leads to the possibility of decryption using any other pair of identical keyfiles. This is a fundamental problem of picocrypt architecture. Fixing it would break backwards compatibility. This problem should at least be documented. An option to solve the problem: detect the use of identical key files and notify the user about the risks.

**Comment by HACKERALERT** [comment]
Yeah I've noted this in the changelog so I will fix it in the next release.
