### ISSUE TITLE
Introduce test coverage 

### ISSUE THREAD

**Issue by SemanticBeeng** [HACKERALERT/Picocrypt#175]
Without test coverage for at least the main claims/features it is hard to trust for production use cases.
Example: https://github.com/diba-io/carbonado/blob/main/tests/apocalypse.rs

Very valuable key features!

**Comment by HACKERALERT** [comment]
Yup, I agree with you that tests will be a good addition. However, how would tests work for Picocrypt, which is a GUI app?

**Comment by SemanticBeeng** [comment]
We could refactor the core functionality separate from UI.

**Comment by HACKERALERT** [comment]
Possibly, but that would be very difficult to do because the UI is tightly integrated with the core functions and decoupling it would probably introduce more bugs than it fixes.

**Comment by SemanticBeeng** [comment]
How would one know there are bugs unless there are tests to prove it? :-)

**Comment by HACKERALERT** [comment]
Yeah no worries, I completely understand the concern. The tests would only cover a very specific set of cases, though, and most bugs occur in edge cases that can't be predicted and must be found through users using the software in the real world. Of course, I don't have much experience with code tests, so I'm not the best to speak for it.
