### ISSUE TITLE
Picocrypt for AArch64/ARM64 macOS

### ISSUE THREAD

**Issue by valynor** [HACKERALERT/Picocrypt#181]
Please consider making available a macOS ARM64 version of Picocrypt as a direct download. 
The times of Intel Macs are over since 2020. :) 

Windows for ARM64 will probably be a popular thing very soon, too.

**Comment by HACKERALERT** [comment]
@valynor I don't have an Apple Silicon Mac so I can't build native binaries for ARM. You can still compile it yourself natively though.

For Windows, I don't think ARM64 adoption will be very fast, it'll take at least 5 years imo for ARM64 to overtake x86. Even then, WoA has x64 emulation built in, so just providing a standard x64 binary will suffice for now.

**Comment by HACKERALERT** [comment]
Feel free to reopen if you have any additional comments :)

**Comment by ZingyAwesome** [comment]
Hello and thanks for your work on the project :)
GitHub actions now has runners for ARM64 macOS, would it be possible to use that to publish an ARM64 build?

**Comment by HACKERALERT** [comment]
Never used runners, and even if I did, I wouldn't be able to test it.

I'm spinning up a Scaleway M1 Mac so hopefully I can compile it from here, but if not, so be it.

**Comment by HACKERALERT** [comment]
@valynor @ZingyAwesome Good news, native binaries coming soon! Gonna put them here and I need you guys to help me test. Expect something from me in two hours.

**Comment by HACKERALERT** [comment]
@valynor @ZingyAwesome Please confirm that this native ARM .app runs on your systems :)
[Picocrypt-arm64.zip](https://github.com/HACKERALERT/Picocrypt/files/15144767/Picocrypt-arm64.zip)

**Comment by HACKERALERT** [comment]
Can anyone confirm that the arm64 binary works on Apple Silicon?

**Comment by dsm** [comment]
I can't run damaged file error

**Comment by ANiceCupOfTea** [comment]
> Can anyone confirm that the arm64 binary works on Apple Silicon?

Doesn't work for me. Tested on M1 Pro.

"Picocrypt is damaged and can’t be opened. You should eject the disk image."

**Comment by HACKERALERT** [comment]
@ZingyAwesome I encountered the same issue, so I recall doing `xattr -c Picocrypt.app`. Looking up xattr, -c clears attributes, -d deletes, so I guess both our commands accomplish the same thing. Do you know which is "better"? If so, I should probably add one of these two commands to the README.

@dsm @ANiceCupOfTea Can you guys confirm whether `xattr -c Picocrypt.app` solves the issue?

**Comment by valynor** [comment]
@HACKERALERT  Thank a lot for making this available so quickly. 🙏

**Comment by HACKERALERT** [comment]
Closing, feel free to reopen if running the xattr command doesn't work.

**Comment by HACKERALERT** [comment]
@valynor @ZingyAwesome @dsm @ANiceCupOfTea 

New automated builds via GitHub Actions for macOS arm64! Need help testing though. Can someone confirm this works? Ping me if it works.

https://github.com/Picocrypt/Picocrypt/actions/runs/9622314576/artifacts/1626906959

**Comment by ZingyAwesome** [comment]
@HACKERALERT
The app works, usual workaround using `xattr` is required.
Slight oddity of there being a nested zip (i.e. Picocrypt.zip is inside build-macos.zip), that is all.

Thank you for your work :)

**Comment by HACKERALERT** [comment]
Yeah, its because .apps are folders and artifacts can only be files..it's a small slight inconvenience but now macOS builds are always native and up to date without my manual work ;)
