### ISSUE TITLE
Problem with running on Linux

### ISSUE THREAD

**Issue by hakavlad** [HACKERALERT/Picocrypt#182]
>Linux users will now get a raw executable binary instead of an AppImage for better portability across distros

BTW this doesn't work on Debian 11:

```
$ ./Picocrypt
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Picocrypt)
```
No such problem with 1.32. 

1.33 has the same problem

**Comment by HACKERALERT** [comment]
I'm building on Debian 12, so it's probably not backward compatible with 11. I'd argue this is okay since a few months from now, most people will be on Debian 12 or Ubuntu 24. Better be future proof for good measure :)

**Comment by hakavlad** [comment]
@CodeCracker-oss 2.31

@HACKERALERT I opened this just for you information.

**Comment by hakavlad** [comment]
Thanks.

**Comment by HACKERALERT** [comment]
Thanks for all the info. I think this is something we safely dismiss with time.
