### ISSUE TITLE
Arm package broken ?

### ISSUE THREAD

**Issue by remihuber** [HACKERALERT/Picocrypt#188]
Macos says that the ARM package is broken when trying to launch Picocrypt.

**Comment by HACKERALERT** [comment]
Please do not create issues here, they go in the new repository and organization. Go there and read the macOS download section, you'll find a command to fix it.

**Comment by remihuber** [comment]
Hi, sorry I come from : https://www.privacytools.io/secure-file-encryption

I am not used to.
That's the link they provide.
Do you want me to erase my "issue post" ?

**Comment by HACKERALERT** [comment]
No it's all good! The move was recent so I'm not expecting everyone to see it.
