### ISSUE TITLE
Webinterface for this tool?

### ISSUE THREAD

**Issue by Tutturuuu** [HACKERALERT/Picocrypt#2]
I dont really know where to put a feature request so i will just post it here. What about a Webinterface for the tool? That way ot would not even require to be installed and would even work on Android. Of course there are some security flaws whith thus design(especially since the encryption would have to happen on a potentially compromised server) but it would still be nice to have over LAN.

**Comment by HACKERALERT** [comment]
Interesting idea. Currently, I have some more important features and fixed that I need to implement, so Android support is something for the (not-too-distant) future. I will add your request to the Roadmap. Thanks! (Reopen this Issue if you feel like I missed something)
