### ISSUE TITLE
Update the executable icon with high definiton ones

### ISSUE THREAD

**Issue by umitseyhan75** [HACKERALERT/Picocrypt#20]
Support at least 256x256 size for the .ico file which is todays standart.
Preferably under PNG container for better quality.
Also provide lower sizes for ensuring compability.
Sample Icon group size chart:
16x16
32x32
48x48
64x64
96x96
128x128
256x256

**Comment by HACKERALERT** [comment]
No problem, I will look into it. I know that an icon is possible, I just didn't get a chance to add one in v1.13. It turns out that I can just add a .ico using Resource Hacker named "GLFW_ICON" and it will work. I'll keep this Issue open and send you a test one when 1.14 is almost complete.

**Comment by HACKERALERT** [comment]
Took me quite a while to find a free converter online that can actually do 256x256, but I finally did and here it is. I'm not too familiar with PNG containers and having multiple resolutions, so I don't think I'll go that far. The 256x256 .ico is actually remarkably clear compared to my old one, and the scaling shouldn't be too bad. If you have any suggestions, let me know.

[icon.zip](https://github.com/HACKERALERT/Picocrypt/files/6837385/icon.zip)

**Comment by umitseyhan75** [comment]
Do you have the 1024x1024 source file?

**Comment by HACKERALERT** [comment]
I don't think so, I only have a 512x512, which is the max that flaticon.com, where I got the icon, allows. They used to allow .svgs, but they stopped offering it as a .svg, and I think I don't have a copy of it. I'll try to find the old .svg from my trash, etc. and I'll let you know if I can find it.

**Comment by HACKERALERT** [comment]
Success, I found it! Turns out that I embedded the .svg while making the logo in a PowerPoint (which I exported into Inkscape for other enhancements). I just right-clicked the image and saved it onto my PC again and voila, there it is!
[key.zip](https://github.com/HACKERALERT/Picocrypt/files/6841295/key.zip)

**Comment by umitseyhan75** [comment]
Great! Working on it now.

**Comment by umitseyhan75** [comment]
Ok. here is the result. It is a multilayered .ico

I create it from the .svg you provide. Exported an 2048x2048 png container from it using GIMP.

It includes 19 layer. 32 bit color depth ones combined with true color + alpha channel transparency.

3x 16x16: 4, 8 and 32 bit
1x 20x20: 32 bit
1x 24x24: 32 bit
3x 32x32: 4, 8 and 32 bit
1x 40x40: 32 bit
2x 48x48: 8 and 32 bit
1x 64x64: 32 bit
1x 128x128: 32 bit
1x 256x256: 32 bit (compressed with loseless PNG compression)
1x 512x512: 32 bit (compressed with loseless PNG compression)
1x 768x768: 32 bit (compressed with loseless PNG compression)
1x 1024x1024: 32 bit (compressed with loseless PNG compression)

[key1.zip](https://github.com/HACKERALERT/Picocrypt/files/6841875/key1.zip)

**Comment by umitseyhan75** [comment]
Looks like fitting.
![ResourceHacker_u1Ar8d8804](https://user-images.githubusercontent.com/43583375/126180878-eb6284bd-6693-46af-a330-5eace2079fd2.png)

**Comment by HACKERALERT** [comment]
You are the man 🙏 ! I would never have been able to do this on my own 😆 . So I just add the .ico as I normally would, right? Thanks so much.

**Comment by umitseyhan75** [comment]
> 
> 
> You are the man 🙏 ! I would never have been able to do this on my own 😆 . So I just add the .ico as I normally would, right? Thanks so much. BTW, does the .ico filename matter?

No problem. I do not know what you mean with "normally". I just added the .ico on Resource Hacker and it looks like working. Besides I also do not know how programming things work. I just created what you need. Seems like the rest is up to you.

**Comment by HACKERALERT** [comment]
>  I do not know what you mean with "normally"

Sorry, I might have been ambiguous about this. I just mean "Add an Image or Binary Resource". I just tested it and it works well. I'll send over a test program in a sec and you can verify that it's correct, since this is not my area of expertise.

**Comment by HACKERALERT** [comment]
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/6842031/Picocrypt.zip)

**Comment by umitseyhan75** [comment]
Open RH
Drag and drop the executable
Click on "add binary or image resoruce"
Click "select file"
Select the .ico I just created (windows.hires1024x1024.ico)
Resource type and name should been entered automatically (ICONGROUP)
Click "add resource"
Click Save

That is how I did.

**Comment by HACKERALERT** [comment]
Yup, same. I did rename it to "GLFW_ICON" because Picocrypt's UI is based on GLFW which requires that particular name for the icon to show.

**Comment by umitseyhan75** [comment]
> 
> 
> Yup, same. I did rename it to "GLFW_ICON" because Picocrypt's UI is based on GLFW which requires that particular name for the icon to show.

You are the one who knows things, what can I say :)

**Comment by HACKERALERT** [comment]
:) I think this thread is complete, right? I'll add the high res icon in future releases.

**Comment by umitseyhan75** [comment]
Gimme a sec!

**Comment by HACKERALERT** [comment]
No problem, take your time!

**Comment by umitseyhan75** [comment]
Looks like MacOs version comes with the next release, so it will need an icon either and .ico extension is not compatible with MacOs.
So here is the **.icns**

Scales for HIDPI Retina display, rest 24 bit

16x16 @2X scale (PNG Compressed)
16x16 32 bit
32x32 @2X scale (PNG Compressed)
32x32 32 bit
48x48 21 bit
64x64 (PNG Compressed)
128x128 @2X scale (PNG Compressed)
128x128 (PNG Compressed)
256x256 @2X scale (PNG Compressed)
256x256 (PNG Compressed)
512x512 @2X scale (PNG Compressed)
512x512 (PNG Compressed)

[mac512.zip](https://github.com/HACKERALERT/Picocrypt/files/6842223/mac512.zip)

**Comment by umitseyhan75** [comment]
Can be closed now.

**Comment by HACKERALERT** [comment]
Ayy, thank you so much! I'm not quite sure how to change icons on macOS, since there is no "Resource Hacker", but I'm sure that I'll be able to Googlefu it out!
