### ISSUE TITLE
Provide Filename Encryption as an Option

### ISSUE THREAD

**Issue by umitseyhan75** [HACKERALERT/Picocrypt#23]
Those namings can be considered as metadata leakage and this is not matching with Picocrypt's ideology.

**Comment by HACKERALERT** [comment]
Can you describe this a little more?

**Comment by umitseyhan75** [comment]
The encryped files still has the same names as input files. Let's say we have a file named as `sample.jpg` and we encrypted it with Picocrypt. The output file will be named as `sample.jpg.pcv`. So it is still obvious what is this. But can be something like `asdfght465adada14s65d4adas6d4a6sd4as6d`
Crypomator has this future, you can check this out!

**Comment by HACKERALERT** [comment]
Oh, I see what you mean. You can just change the name in the text box or click the "Choose" to save it as a custom name. Would you prefer a button to generate a random name?

**Comment by umitseyhan75** [comment]
I prefer filenames be encrypted with the encrpytion key which encrypt the file's itself rather than my random typing.

**Comment by HACKERALERT** [comment]
I think I get what you mean... So you would like to be able to have random file names when encrypting a file, but for the encrypted file to decrypt to the correct file name (original file name encrypted and stored in file)? Example:

Input: test.txt
Encrypted file: 2340aws0f78z7s0e8a028347a08w70zs870zw83740987.pcv
Decrypted file: test.txt

**Comment by umitseyhan75** [comment]
> random file names when encrypting a file
I do not know the technical details of this operation that much but I belive the "random" word is not the word I am talking about as we are talking about encryption keys. But yes, I am talking about this kind of thing.

**Comment by HACKERALERT** [comment]
Alright, no problem! I will make a note of it and I'll keep this Issue updated with progress. Thanks for your suggestion!

**Comment by umitseyhan75** [comment]
Rclone also has this future as another example, as you are a developer, you can understand how it is happening by looking at their code. Sorry for can not providing in-depth information.

**Comment by HACKERALERT** [comment]
Great, I will look into it.

> Sorry for can not providing in-depth information.

No worries at all! Suggesting this is all that is needed on your end, I can take care of the rest.

**Comment by Zyxyx** [comment]
I guess this is somewhat similar to the following one...
Feature Request : File & Folder Names Obfuscation - #14

So Kryptor might be another source of inspiration.
Thank you for considering to implement this.

**Comment by HACKERALERT** [comment]
After a while, I've decided to not add filename encryption to Picocrypt, mostly because of the complexities of encrypting the filename, decrypting to a temporary file and then renaming to the decrypted name, etc. You can always rename the file before or after encryption, so this would be an enhancement that is not really worth the extra code and complexity.
