### ISSUE TITLE
Feature request: Watch input folder for new files and encrypt any added files

### ISSUE THREAD

**Issue by Duckle29** [HACKERALERT/Picocrypt#34]
I'd like to have a folder that I can throw files in, and they'll automatically get encrypted and moved to an output folder.

My use-case for this is encrypting text files with my 2FA backup codes, and then storing them in my nextcloud instance. I'd love if this could work using a public/private key implementation, but wouldn't mind if it popped up to ask for a password either.

**Comment by HACKERALERT** [comment]
I think gocryptfs does exactly what you want:
![](https://raw.githubusercontent.com/rfjakob/gocryptfs/master/Documentation/folders-side-by-side.gif)

**Comment by Duckle29** [comment]
Dang that looks pretty neat
sadly I'm on windows :/

**Comment by HACKERALERT** [comment]
To keep Picocrypt simple and cross-platform, I don't think I will be implementing this, since it has a specific use case and would not really work with Picocrypt's ideology. Thanks for the request, though!
