### ISSUE TITLE
Selecting all checksum boxes by default

### ISSUE THREAD

**Issue by ThisIsNotANamepng** [HACKERALERT/Picocrypt#36]
Maybe it's because I'm still on 1.17, but when dragging a file into the checksum generator, it would be much easier if all of the boxes were checked by default. Otherwise, it's just a hassle when I drop a file in and none of the boxes are checked, which means I have to check the ones I want and then find the file again

**Comment by HACKERALERT** [comment]
Interesting. The thing is though, if all of them were checked and you dropped a large file, it would take a very long time to generate all of them... But I do agree that it's a good idea to have them checked by default. I'll hold on to this issue for now and I'll do a poll some time and see what others think. Thanks for pointing this out!

**Comment by ThisIsNotANamepng** [comment]
True. Thank you, totally!

**Comment by ThisIsNotANamepng** [comment]
Sounds good!

**Comment by HACKERALERT** [comment]
Great :)
