### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by ThisIsNotANamepng** [HACKERALERT/Picocrypt#37]
If you turn the page to a language other than English, go to the shredder tab, turn it back to English, and go back to the shredder tab, the last line on the bottom that says "Ready." in English will still be in the language it was set to

Also, every language except for Spanish has a "." after it's equivalent of "Ready."

**Comment by HACKERALERT** [comment]
Thanks for pointing this out! I'll be needing a retranslation soon, so I should be able to fix this issue then.
