### ISSUE TITLE
Add .zip to filename when custom output location is chosen

### ISSUE THREAD

**Issue by Inrumpo** [HACKERALERT/Picocrypt#38]
I'm currently testing Picocrypt because I like the idea and functionality behind this lightweight tool. I believe my rather "non-techy" perspective can be of value (in terms of expectations and workflow).

## Usecase
As a user I want to chose a custom output (~ save to) location for my decrypted folder. This option is available; but:

## Possible issue
I navigate to my desired location and define a file name without adding an extension. The file type drop-down menu is empty. I just leave it that way (especially because I can't select anything anyways). This results in a decrypted file without a file type that is somewhat unusable for a non-techy user. Solution: I should have added `.zip` to my filename.

So far I've only tested this with a folder (→ .zip). Doing this with a single file might lead to a similar experience.

## Possible solution
Force add the correct file extension or provide an exemplary file name (e.g. based on encrypted file name) in the explorer window including the correct file extension instead of leaving it empty.

## Environment

- Windows 10, 64bit
- Version 1.17 stable

**Comment by HACKERALERT** [comment]
@Inrumpo Thanks for your interest and this post! I really like the format you've put it in 😄 .

Indeed, this is an issue that hasn't been fixed up to v1.17. I should have a working fix in v1.18, and I've attached a preview for v1.18. Would you mind testing it out and letting me know if this issue persists? Thank you!

[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/7213165/Picocrypt.zip)

**Comment by Inrumpo** [comment]
> Would you mind testing it out and letting me know if this issue persists?

Sure.
There are a few UI things with that version but the described issue is fixed. This version will add the `.zip` extension automatically. ✅

Thanks for the quick fix!
