### ISSUE TITLE
Windows Installer version (fix 7-Zip dependency)

### ISSUE THREAD

**Issue by beerisgood** [HACKERALERT/Picocrypt#4]
Providing an installer for Windows solve the following problem:
> The portable .exe can be detected as a virus, because it uses 7-Zip's self-extracting archive format to bundle Python along with Picocrypt

**Comment by HACKERALERT** [comment]
Sure, I can also provide an installer, but that will also be flagged because I don't have a certificate (hundreds of dollars a year) to sign the executables. As long as people submit Picocrypt as a false positive to antivirus providers, everything will be fine.

**Comment by HACKERALERT** [comment]
If you are good, are we done with this issue?
