### ISSUE TITLE
Text not fully readable in GUI / App does not adjust to Windows scaling

### ISSUE THREAD

**Issue by BigPanda97** [HACKERALERT/Picocrypt#43]
![2021-09-26 14_51_11-Picocrypt](https://user-images.githubusercontent.com/91138677/134808853-e56a9295-ea57-42bc-a09d-aee61e6f4bbb.png)

Text is overlapping at the “Advanced” section, and the window size is fixed, so I can't make it readable.
(See screenshot)

Windows 10, 1920×1080 screen resolution, scaling is at 125%. (So the app should/must adjust for the selected scaling of the Windows resolution.)

**Comment by HACKERALERT** [comment]
That's really weird. The UI scaling has been an issue for a while, I'm going to hop on my high DPI laptop to see what the issue is and fix it!

**Comment by HACKERALERT** [comment]
This is indeed an issue, it is apparent on my laptop. Give me a few hours to fix it.

**Comment by HACKERALERT** [comment]
Can you test this and let me know if the UI scales correctly? Thanks!
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/7231965/Picocrypt.zip)

**Comment by BigPanda97** [comment]
The original issue is fixed now, but the "Clear" button behaves strange now if the filename is very long...

![2021-09-26 20_52_45-Picocrypt](https://user-images.githubusercontent.com/91138677/134820524-7163cc0a-831c-4858-a303-c454a8adb559.png)

(The button moves more and more to the left, the longer the filename is.)

**Comment by HACKERALERT** [comment]
Hmm, correct me if I'm wrong but I don't see why a person would have that long of a filename 😅

**Comment by BigPanda97** [comment]
> Hmm, correct me if I'm wrong but I don't see why a person would have that long of a filename 😅

The file name isn't that long, lol. This happened with the name of the screenshot too, but I replaced it with the text you see above for privacy reasons.

And the button starts to move already at any name with more than 65 characters...

**Comment by HACKERALERT** [comment]
Oh, I see 😄 . Thanks for the clarification. I'll do some digging and hopefully I can fix the issue!

**Comment by HACKERALERT** [comment]
I think I've fixed it. Would you mind confirming that long file names work?
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/7232313/Picocrypt.zip)

**Comment by BigPanda97** [comment]
Yes, it works now. :)

**Comment by HACKERALERT** [comment]
Awesome! I'll release v1.19 shortly as a bug fix update that will incorporate this fix.
