### ISSUE TITLE
Potential data races for variables used by UI elements

### ISSUE THREAD

**Issue by Zacho2** [HACKERALERT/Picocrypt#45]
On inspection I see a handful of potential data races. There are many cases where UI elements modify something in memory that may be simultaneously used by I/O related code (and vice versa). 

For example `stopShredding` https://github.com/HACKERALERT/Picocrypt/blob/main/src/Picocrypt.go#L219 is bound to a UI action https://github.com/HACKERALERT/Picocrypt/blob/main/src/Picocrypt.go#L912 which will write to `stopShredding` in a different context than where it's consumed https://github.com/HACKERALERT/Picocrypt/blob/main/src/Picocrypt.go#L2174

Seems like most of the shredding related variables have this issue.

**Comment by HACKERALERT** [comment]
Correct me if I'm wrong, but the `stopShredding` variable is meant to be changeable to UI action (the "Cancel" button) and it's supposed to be checked in the shredding context to decide with the user has cancelled the shredding process or not...
