### ISSUE TITLE
translation for Chinese

### ISSUE THREAD

**Issue by qaqland** [HACKERALERT/Picocrypt#48]
my time will spare in about two-months future.
wait me!

**Comment by qaqland** [comment]
why your use forks instead of original
🤔

is there any plan for Unicode display thus I can translate the app itself

**Comment by HACKERALERT** [comment]
> why your use forks instead of original

?

I am planning to have a file with the translations for the UI itself soon.

**Comment by qaqland** [comment]
![IMG_20220103_222608.jpg](https://user-images.githubusercontent.com/62464571/147941961-ce55965e-0958-4b31-b383-39d29be2aebe.jpg)

Here the import are all from you
I am a beginner in go. I can't understand it

**Comment by HACKERALERT** [comment]
I forked each dependency so in case the original author deletes it, I will still have my own forks of them and nothing will be lost.

**Comment by HACKERALERT** [comment]
For now, the main GitHub README would be good for translation. And in the future, I will have the UI ready for translation as well. Those are the only things needing translation, and you won't need to translate dependencies. So for now, you can begin translating the README if you would like. Let me know if there is any confusion!

**Comment by qaqland** [comment]
I understand !
I wait for the UI to support translation. 
the readme is too more words for me and I will not do it

**Comment by HACKERALERT** [comment]
Cool, no problem! I'll let you know when the UI is ready for translation.

**Comment by HACKERALERT** [comment]
I'll close for now to keep things tidy, but I will let you know when things are ready.
