### ISSUE TITLE
Folder support

### ISSUE THREAD

**Issue by beerisgood** [HACKERALERT/Picocrypt#5]
With https://github.com/HACKERALERT/Picocrypt/issues/4 a context menu via right click can provide such a feature.

**Comment by HACKERALERT** [comment]
I don't quite get what you mean. If you want to encrypt a fder, you can just add it to a .zip.

**Comment by beerisgood** [comment]
Like i wrote a context menu entry which encrypt all files in that specific folder so encrypting files manually isn't needed.
Using .zip isn't what i mean.

**Comment by HACKERALERT** [comment]
So, you have a pull request? Or do you mean that you'd like a feature to encrypt all files in a folder? Please elaborate 👍 .

**Comment by beerisgood** [comment]
Yeah i would like such a feature but can't provide a pull request.

**Comment by HACKERALERT** [comment]
Alright, can you describe in detail about how this feature works? I think you mean to add an entry to Windows explorer that says "Encrypt this folder with Picocrypt". Am I right?

**Comment by beerisgood** [comment]
Right!

**Comment by HACKERALERT** [comment]
Alright, I'll add it to the Roadmap and look into it. I'm closing this issue now, but feel free to reopen it if necessary. Thanks!

**Comment by beerisgood** [comment]
Thanks for adding this in version 1.11 🍺
