### ISSUE TITLE
Removed SECURITY.md file

### ISSUE THREAD

**Issue by samuel-lucas6** [HACKERALERT/Picocrypt#51]
> In the unlikely scenario that a security vulnerability is discovered, please draft a security advisory in the Security tab of this repository and I will fix it as soon as possible.

Only people with [admin permissions](https://docs.github.com/en/code-security/security-advisories/creating-a-security-advisory) can draft security advisories, which is why there should be a separate [SECURITY.md](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) file.

**Comment by HACKERALERT** [comment]
Thank you for letting me know, I didn't know that. I will add it back soon.

**Comment by HACKERALERT** [comment]
Added, thanks for pointing this out. I was not expecting GitHub to require admin permissions to report a security issue...
