### ISSUE TITLE
AUR package for Arch or AppImage

### ISSUE THREAD

**Issue by bambirombi** [HACKERALERT/Picocrypt#68]
I have tried installing with snap in arch linux but it does not work. It will be interesting and arch package or an appimage.

**Comment by HACKERALERT** [comment]
Thanks for letting me know. I don't have a lot of experience with Linux, so I don't have the ability to create AppImages yet. I also have trouble installing Arch, lol, so I'm not sure how to compile for it when I can't get it installed. Don't worry though, I'll get things fixed eventually, probably be replacing the Snap with a Flatpak.

**Comment by HACKERALERT** [comment]
To anyone reading this, if you have experience with packaging tools and are willing to help me package Picocrypt, please let me know. Thanks.

**Comment by Etim-Orb** [comment]
I just want to chime in that if you need an Arch based distro with an easy installer I recommend EndeavourOS.

**Comment by HACKERALERT** [comment]
Okay, so after some thinking, I won't be adding any AUR or Arch package. I'm not experienced with Arch, and don't believe it will be worth the time. Getting a Snap working is hard enough. And since the Snap already works on Arch, it is good enough, for now at least.
