### ISSUE TITLE
Does picocrypt support both argon2d and argon2id ?

### ISSUE THREAD

**Issue by Jrchintu** [HACKERALERT/Picocrypt#73]

**Comment by HACKERALERT** [comment]
@Jrchintu Picocrypt only supports Argon2id because only Argon2id and Argon2i are exposed by Go's extended cryptography library.

**Comment by Jrchintu** [comment]
> @Jrchintu Picocrypt only supports Argon2id because only Argon2id and Argon2i are exposed by Go's extended cryptography library.

Thank's for that quick reply. I just got confused between both, everything clear now. I am closing this issue with quoting this as answer.
