### ISSUE TITLE
Malware alert version 1.24

### ISSUE THREAD

**Issue by 101110000** [HACKERALERT/Picocrypt#76]
Kaspersky Anti-Virus: **Trojan.Win32.Wofith.hqa**
Picocrypt.exe
MD5: 5B7F59847E19C475FE2F89DAA98446FC

**Comment by HACKERALERT** [comment]
I can't do anything about it, please submit it as a false positive.

**Comment by 101110000** [comment]
I already did. I'm waiting...
Dynamic scan found 2 malware:

```
Trojan.Win32.Wofith.hqa
Trojan.Win32.Wofith.sb
SHA-256: 0E49003E1D64500F269647148BD7463CBECAAB59BD96E44A1C85DBD0ED05C6BD
```

**Comment by HACKERALERT** [comment]
Okay. It'll take some time for Kaspersky to verify that Picocrypt is a false positive and push the signature update to your PC.

**Comment by 101110000** [comment]
False positive verified. It will be fixed.

**Comment by 101110000** [comment]
Thanks for nice work.

**Comment by HACKERALERT** [comment]
Great, thanks for the help!
