### ISSUE TITLE
Picocrypt don't start

### ISSUE THREAD

**Issue by JackJeisly** [HACKERALERT/Picocrypt#83]
Hello, in xUbuntu 20.04 Picocrypt show error:
```
$ picocrypt
panic: failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

goroutine 1 [running, locked to thread]:
github.com/HACKERALERT/giu.NewMasterWindow({0x8b4d1d, 0x9}, 0x13e, 0x1df, 0xa0?)
	/root/go/pkg/mod/github.com/!h!a!c!k!e!r!a!l!e!r!t/giu@v0.5.7-0.20220411212054-a37934efe9a9/MasterWindow.go:73 +0x626
main.main()
	/root/parts/picocrypt/build/Picocrypt.go:1719 +0x38
```
As i understand problem with openGL version. 
How correct it?
Thank!

**Comment by HACKERALERT** [comment]
I am not too sure. Linux is always buggy when it comes to drivers. It should not be an OpenGL version issue, as long as your CPU was manufactured later than 2009, which is when the minimum OpenGL version needed by Picocrypt was released. Your CPU most likely supports OpenGL, it's just your OS lacks the drivers.

Is there an "Additional Drivers" app in your applications, or a tab like that in your settings? Because if your OS doesn't support OpenGL, there's nothing I can do, unfortunately. Installing packages won't help either, since OpenGL is a firmware thing and not a software issue. I'm not experienced with Linux, so I can't be of much help :|

**Comment by JackJeisly** [comment]
I have a standart OpenGL version 1.3.2 in system. So i doesn't have any ideas. :(

I tried compile v.1.2.5 from source code, but i got error:
root@mypc:/home/mypc/Downloads/Picocrypt-1.25/src# go build -ldflags="-s -w" Picocrypt.go

build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element

**Comment by HACKERALERT** [comment]
OpenGL 1.3 is really outdated. It was released in 2001 (https://www.khronos.org/opengl/wiki/History_of_OpenGL). At least OpenGL 3.2 is required for Picocrypt to run, so I'm not sure what can be done either, other than to not use Linux 🤷. Building from source won't change anything since OpenGL is required at runtime, not compile time.

**Comment by HACKERALERT** [comment]
What are your system specs? CPU, memory, etc.

**Comment by JackJeisly** [comment]
Ubuntu 20.04.4 LTS

CPU intel
Penryn (Core 2 Duo) 3M
Intel(R) Core(TM)2 Duo CPU T8300 @ 2.40GHz
MMX, SSE(1, 2, 3, 3S, 4.1), VT-x, x86-64

Memory 
2x: Nanya Technology NT2GT64U8HD0BN-3C 
 2048 MB @ 667MHz (SODIMM DDR2)

Grafics
Card 0:
Vendor: Intel (i915 driver)
Model: Mobile GM965/GL960 Integrated Graphics Controller (primary)

Card 1
Vendor: Intel Mobile GM965/GL960 Integrated Graphics Controller (primary)
Model: Mobile GM965/GL960 Integrated Graphics Controller (secondary)


# cat /proc/version
Linux version 5.13.0-30-generic (buildd@lcy02-amd64-003) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #33~20.04.1-Ubuntu SMP

# glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) 965GM (CL)
OpenGL version string: 2.1 Mesa 21.2.6
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

**Comment by JackJeisly** [comment]
Hardware info:
```

# lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           23
Model name:                      Intel(R) Core(TM)2 Duo CPU     T8300  @ 2.40GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         1850.536
CPU max MHz:                     2401,0000
CPU min MHz:                     800,0000
BogoMIPS:                        4787.94
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        3 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no mic
                                 rocode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disab
                                 led, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ht tm pbe syscall nx lm constant_t
                                 sc arch_perfmon pebs bts rep_good nopl cpuid ap
                                 erfmperf pni dtes64 monitor ds_cpl vmx est tm2 
                                 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm pti tpr_sha
                                 dow vnmi flexpriority vpid dtherm ida
```

```
# lspci
00:00.0 Host bridge: Intel Corporation Mobile PM965/GM965/GL960 Memory Controller Hub (rev 0c)
00:02.0 VGA compatible controller: Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller (primary) (rev 0c)
00:02.1 Display controller: Intel Corporation Mobile GM965/GL960 Integrated Graphics Controller (secondary) (rev 0c)
00:03.0 Communication controller: Intel Corporation Mobile PM965/GM965 MEI Controller (rev 0c)
00:03.2 IDE interface: Intel Corporation Mobile PM965/GM965 PT IDER Controller (rev 0c)
00:03.3 Serial controller: Intel Corporation Mobile PM965/GM965 KT Controller (rev 0c)
```

**Comment by HACKERALERT** [comment]
It looks like your CPU is too old and the highest supported OpenGL version is 2.1. So, unfortunately, I don't think you'll be able to use Picocrypt. Consider giving VeraCrypt a try, as it should work natively with Linux.

**Comment by JackJeisly** [comment]
Okay, i try other program.
Thanks!

**Comment by HACKERALERT** [comment]
@JackJeisly The latest version should run for you now, because I've removed the driver requirement and use software rendering instead. Feel free to give Picocrypt another try :P

**Comment by JackJeisly** [comment]
Wow! I test it in xUbuntu 20.04, Appimage and .deb, all work nice.
Thank's very much!

**Comment by HACKERALERT** [comment]
Great to hear! Supporting as many systems as possible has been a focus for the last little while and I guess my work has paid off 😃

**Comment by asakura42** [comment]
@HACKERALERT still doesn't work without video card:

```
panic: failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

goroutine 1 [running, locked to thread]:
github.com/HACKERALERT/giu.NewMasterWindow({0x55e0c2561fab, 0x9}, 0x13e, 0x1fb, 0xa0?)
        github.com/HACKERALERT/giu@v0.5.7-0.20221117223150-211c1da061d9/MasterWindow.go:75 +0x645
main.main()
        ./Picocrypt.go:2260 +0x38
```

with DRI_PRIME=1 (video card enabling switch) all works ok

**Comment by HACKERALERT** [comment]
It works for most devices so that's enough. It's impossible to add workarounds for every device.
