### ISSUE TITLE
Use "Telemetry" or similar wording instead of "Phones home" in comparison chart

### ISSUE THREAD

**Issue by Etim-Orb** [HACKERALERT/Picocrypt#93]
I believe this would make things much more straight forward (and also there's not really an expression for this in Hungarian). Since telemetry is not necessarily a bad thing in IT and phoning home is a term that suggests slight malice and non desired effects there might be a better alternative for "Telemetry", though I still believe this is the most suitable, straight forward and simple word for this.

**Comment by HACKERALERT** [comment]
The current comparison chart does use "Telemetry" at the moment.

**Comment by HACKERALERT** [comment]
Haha now worries :)
