### ISSUE TITLE
Cannot decrypt file on macOS

### ISSUE THREAD

**Issue by mmoga** [HACKERALERT/Picocrypt#96]
I have release 1.27 of Picocrypt installed on an Intel Mac with Monterey 12.3.1. After encrypting a folder, I am unable to decrypt it and receive an error message: **The document “test-folder_secure.zip.pcv” could not be opened. Picocrypt cannot open files of this type.**

The gif below shows the process:

![Picocrypt error](https://user-images.githubusercontent.com/31258808/167517309-9e98f74f-ac63-4428-8af4-da4affa017b9.gif)

Let me know if you need more information—I'm happy to help!

**Comment by HACKERALERT** [comment]
Ah, that is because Picocrypt is portable so it doesn't register file associations. If you drag the .pcv back into Picocrypt, then you can decrypt it.

**Comment by mmoga** [comment]
Oh duh! Thank you for replying so quickly! 🙏

**Comment by HACKERALERT** [comment]
Glad to help!
